# Generated by Django 3.1.7 on 2021-04-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfile',
            name='isfile',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
