# Generated by Django 3.1.7 on 2021-04-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dfile_isfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DFile',
            new_name='File',
        ),
    ]
