# Generated by Django 3.1.7 on 2021-04-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210404_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='isfile',
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.FileField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
